model_path: "meta-llama/Meta-Llama-3-8B-Instruct"
dataset: "Open-Orca/SlimOrca"
dataset_column: "text"
batch_size: 8
max_length: 1024
dataset_size: 128
dataset_subset: "train"
use_4bit: True
save_path: null
min_distance_layer: 20
save_transform_only: True
diag: False # whether to force the LT to be a diagonal matrix
alpha: 0 # regularization factor (use Ridge regularization)
distances_path: "./distances.pth"
num_A: 2
layers_to_skip: 4
merge_consecutive: True 
