model_path: "meta-llama/Meta-Llama-3-8B-Instruct"
dataset: "Open-Orca/SlimOrca"
dataset_column: "text"
batch_size: 8
max_length: 1024
layers_to_skip: 8
dataset_size: 1000
dataset_subset: "train"
activations_save_path: null
use_4bit: True
save_path: null
min_distance_layer: null
