# adaptive_kernel_config.yaml
method: "adaptive_kernel"
model_path: "meta-llama/Meta-Llama-3-8B-Instruct"
dataset: "Open-Orca/SlimOrca"
dataset_column: "text"
batch_size: 8
max_length: 1024
layers_to_skip: 8  # 한 블록당 교체할 레이어 수
num_blocks: 1  # 교체할 블록 수
compression_ratio: 4  # Kernel feature compression ratio
critical_threshold: 0.3  # Top 30% layers are critical
dataset_size: 4000
dataset_subset: "train"
use_4bit: False
save_path: null
distances_path: null  # Optional: pre-computed distances
token: null  # HuggingFace token if needed