# Advanced ReplaceMe configuration
method: "advanced"  # Use the new advanced method
model_path: "meta-llama/Meta-Llama-3-8B-Instruct"
dataset: "Open-Orca/SlimOrca"
dataset_column: "text"
batch_size: 8
max_length: 1024
layers_to_skip: 8
dataset_size: 8000
dataset_subset: "train"
use_4bit: True
save_path: null
min_distance_layer: 20
save_transform_only: False
distances_path: null
num_A: 1
merge_consecutive: False

# Advanced method specific parameters
critical_ratio: 0.3  # Proportion of dimensions to treat as critical (0.3 = 30%)
# Smaller ratio = fewer critical dims = faster computation but potentially less accurate
# Larger ratio = more critical dims = slower but potentially more accurate