method: "bidirectional"
model_path: "meta-llama/Meta-Llama-3-8B-Instruct"
dataset: "Open-Orca/SlimOrca"
dataset_column: "text"
batch_size: 8
max_length: 1024
layers_to_skip: 8
dataset_size: 8000
dataset_subset: "train"
use_4bit: False
save_path: null
distances_path: "distances.pth"
num_A: 1
merge_consecutive: False
accurate: False  # Set to True for more accurate but memory-intensive mode
# Bidirectional specific parameters
rank_ratio: 0.1  # Ratio of hidden dim to use for low-rank correction
num_iterations: 3  # Number of iterative refinement steps