# ============================================================
# cmapt.yaml - CMAPT Configuration
# Cross-Modal Alignment Preserving Transform
# ============================================================

method: "vlm_cmapt"
model_path: "llava-hf/llava-1.5-7b-hf"
image_dir: "train2014"
batch_size: 8
max_length: 512
layers_to_skip: 8
dataset_size: 8000
use_4bit: True
save_path: null
save_transform_only: True

# CMAPT-specific hyperparameters
lambda_output: 1.0      # Weight for output matching (standard ReplaceMe)
lambda_alignment: 0.3   # Weight for cross-modal alignment preservation
lambda_intra: 0.1       # Weight for intra-modal structure preservation

# Optimization settings
lr: 0.0001
num_epochs: 10
opt_batch_size: 1024

# Layer selection
distances_path: null  # Will compute if not provided
num_A: 1
merge_consecutive: False

token: null