# Example configuration for low-rank factorization
model_path: "meta-llama/Meta-Llama-3-8B-Instruct"  # Replace with your 3B model
dataset: "Open-Orca/SlimOrca"
dataset_column: "text"
dataset_subset: "train"
dataset_size: 2000
batch_size: 4
max_length: 512

# Method selection
method: "low_rank"  # New method for low-rank factorization

# Block selection parameters
layers_to_skip: 2  # For 4-block replacement
num_A: 1
merge_consecutive: False
distances_path: null

# Low-rank specific parameters
low_rank: 2048  # Rank for factorization
loss: "cosine"
solver: "adam"

# Other parameters
use_4bit: True
save_transform_only: True
diag: False
thri: False
two_vectors: False
accurate: False

# Evaluation tasks
# tasks:
#   boolq:
#     fewshots: 5
#   lambada_openai:
#     fewshots: 5
#   openbookqa:
#     fewshots: 5
#   piqa:
#     fewshots: 5
#   race:
#     fewshots: 5
#   sciq:
#     fewshots: 5
#   winogrande:
#     fewshots: 5