# Example configuration for GRASP-inspired factorization method
model_path: "microsoft/DialoGPT-medium"  # Replace with your 3B model
dataset: "Open-Orca/SlimOrca"
dataset_column: "text"
dataset_subset: "train"
dataset_size: 2000
batch_size: 4
max_length: 512

# Method selection
method: "grasp_inspired"  # New GRASP-inspired method with activation-based attribution

# Block selection parameters
layers_to_skip: 4  # For 4-block replacement
num_A: 1
merge_consecutive: False
distances_path: null

# GRASP-inspired specific parameters
low_rank: 1024  # Rank for factorization
loss: "cosine"  # Loss function for transformation estimation
solver: "adam"  # Solver for transformation optimization

# Other parameters
use_4bit: True
save_transform_only: True
diag: False
thri: False
two_vectors: False
accurate: False
