# Self-healing ReplaceMe configuration
method: "healme"
model_path: "meta-llama/Meta-Llama-3-8B-Instruct" # meta-llama/Llama-3.2-3B-Instruct
dataset: "Open-Orca/SlimOrca"
dataset_column: "text"
batch_size: 4 # 8
max_length: 512 # 1024
layers_to_skip: 4
dataset_size: 1000 # 8000
dataset_subset: "train"
use_4bit: True
save_path: null
min_distance_layer: 20
save_transform_only: True

# Self-healing specific parameters
healing_threshold: 15.0  # Perplexity threshold for triggering healing

# Transformation parameters (inherited from cosine_dist)
diag: False # whether to force the LT to be a diagonal matrix
two_vectors: False # whether to force the LT to be a multiplication of two vectors
thri: False # whether to force the LT to be a lower triangular matrix
solver: "adam" # adam, cg, l-bfgs, trust-ncg are supported
loss: "cosine" # cosine, mse, elasticnet are supported
accurate: False # False will run cosine(xA, y - z) where z is the residual attention info, True to run cosine(xA + z, y)

# Block selection parameters
distances_path: null
num_A: 1
merge_consecutive: False 

# Evaluation tasks
tasks:
  boolq:
    fewshots: 0
  lambada_openai:
    fewshots: 0