# ============================================================
# hybrid.yaml - Hybrid Teacher-Student Configuration
# Stage 1: ReplaceMe + Stage 2: Teacher-Student Fine-tuning
# ============================================================

method: "vlm_hybrid"
model_path: "llava-hf/llava-1.5-7b-hf"
image_dir: "train2014"
batch_size: 8
max_length: 512
layers_to_skip: 12
dataset_size: 8000
use_4bit: True
save_path: null
save_transform_only: True

# Stage 1: ReplaceMe (fast initialization)
lr_stage1: 0.0001
num_epochs_stage1: 10
opt_batch_size: 1024

# Stage 2: Teacher-Student (refinement)
lr_stage2: 0.00005  # Lower LR for fine-tuning
num_steps_stage2: 100  # Few steps only!

# Layer selection
distances_path: "distances_12.pth"
num_A: 1
merge_consecutive: False

token: null