# ============================================================
# two_phase.yaml - Two-Phase Teacher-Student Configuration
# Phase 1: ReplaceMe baseline (MLP-level)
# Phase 2: Teacher-guided refinement (Layer-level)
# ============================================================

method: "vlm_two_phase"
model_path: "llava-hf/llava-1.5-7b-hf"
image_dir: "train2014"
batch_size: 8
max_length: 512
layers_to_skip: 12
dataset_size: 4000
use_4bit: True
save_path: null
save_transform_only: True

# Two-Phase specific parameters
ensemble_alpha: 0.5      # T_final = 0.5*T_base + 0.5*T_refined

# Phase 1: Standard ReplaceMe (MLP-level)
lr_phase1: 0.0001
num_epochs_phase1: 10

# Phase 2: Teacher-guided (Layer-level)
lr_phase2: 0.00001       # Lower LR for fine-tuning
num_epochs_phase2: 5     # Fewer epochs (already have good init)

# Optimization
opt_batch_size: 1024

# Layer selection
distances_path: "distances_12.pth"
num_A: 1
merge_consecutive: False

token: null