method: "improved"
model_path: "meta-llama/Meta-Llama-3-8B-Instruct"
dataset: "Open-Orca/SlimOrca"
dataset_column: "text"
batch_size: 8
max_length: 1024
layers_to_skip: 8
dataset_size: 4000
dataset_subset: "train"
use_4bit: True
save_path: null
distances_path: "distances_8layer.pth"
num_A: 1
merge_consecutive: False

# Improved ReplaceMe parameters
improved_epochs: 10
improved_lr: 0.0005  # 5e-4
improved_cosine_weight: 0.9
improved_norm_weight: 0.1
improved_init_scale: 0.01