# Example configuration for LOST-inspired factorization
model_path: "meta-llama/Meta-Llama-3-8B-Instruct" 
dataset: "Open-Orca/SlimOrca"
dataset_column: "text"
dataset_subset: "train"
dataset_size: 2000
batch_size: 4
max_length: 512

# Method selection
method: "lost_inspired"  # New LOST-inspired method

# Block selection parameters
layers_to_skip: 4  # For 4-block replacement
num_A: 1
merge_consecutive: False
distances_path: null

# LOST-inspired specific parameters
low_rank: 1024  # Rank for low-rank component
sparsity_ratio: 0.01  # Ratio of channels for sparse component (1% as in LOST paper)
gamma: 0.7  # Trade-off coefficient (0.7 as suggested in LOST paper)
loss: "cosine"
solver: "adam"

# Other parameters
use_4bit: True
save_transform_only: True
diag: False
thri: False
two_vectors: False
accurate: False
