# procrustes_sequential_config.yaml
method: "procrustes_sequential"
model_path: "meta-llama/Meta-Llama-3-8B-Instruct"
dataset: "Open-Orca/SlimOrca"
dataset_column: "text"
batch_size: 4
max_length: 512
layers_to_skip: 4
dataset_size: 2000  # 50k calibration data as discussed
dataset_subset: "train"
use_4bit: True
save_path: null
token: null

# Distance profiling (if not already computed)
distances_path: null  # Will auto-compute if null

# Block selection parameters
num_A: 3  # Number of transformer block groups to replace
merge_consecutive: False

# ProcrustesGPT specific parameters
sequential_constraint_weight: 0.1  # Weight for sequential dependency loss
orthogonal_regularization: 0.01    # Orthogonality constraint strength

# Evaluation tasks (optional)
tasks: "default"