# ============================================================
# mlm.yaml - Multi-Layer Matching Configuration
# Teacher-student inspired multi-layer supervision
# ============================================================

method: "vlm_mlm"
model_path: "llava-hf/llava-1.5-7b-hf"
image_dir: "train2014"
batch_size: 8
max_length: 512
layers_to_skip: 12
dataset_size: 8000
use_4bit: True
save_path: null
save_transform_only: True

# MLM-specific parameters
weight_strategy: "linear_increasing"  # linear_increasing, exponential, uniform

# Optimization (same as ReplaceMe for fair comparison)
lr: 0.0001
num_epochs: 10
opt_batch_size: 1024

# Layer selection
distances_path: "distances_12.pth"
num_A: 1
merge_consecutive: False

token: null