method: "arm"
model_path: "meta-llama/Meta-Llama-3-8B-Instruct"
dataset: "Open-Orca/SlimOrca"
dataset_column: "text"
batch_size: 2  # 8
max_length: 256
layers_to_skip: 4 # 8
dataset_size: 1000 # 8000
dataset_subset: "train"
use_4bit: True
save_path: null
save_transform_only: True

# ARM specific parameters
soc_temperature: 75.0  # Current SoC temperature in Celsius
use_attention_gating: True  # Use attention pattern analysis
use_multi_scale: True       # Use position-aware transforms
use_residual_aware: True    # Model residual connections explicitly

# Existing ReplaceMe parameters (for compatibility)
distances_path: null
num_A: 1
merge_consecutive: False 
accurate: False
min_distance_layer: 20

# Tasks for evaluation
tasks: 
  winogrande:
    fewshots: 5
  # boolq:
  #   fewshots: 0
  # piqa:
  #   fewshots: 0
  # race:
  #   fewshots: 0
  # openbookqa:
  #   fewshots: 0
  # sciq:
  #   fewshots: 0