# Enhanced Cosine Method Configuration
method: "enhanced_cosine"  # NEW: Our enhanced method
model_path: "meta-llama/Meta-Llama-3-8B-Instruct"
dataset: "Open-Orca/SlimOrca"
dataset_column: "text"
batch_size: 4  # Reduced batch size for memory efficiency
max_length: 1024  # Reduced sequence length
layers_to_skip: 4
dataset_size: 4000  # Reduced dataset size
dataset_subset: "train"
use_4bit: True
save_path: null
min_distance_layer: 20
save_transform_only: True
loss: "cosine"  # cosine, mse are supported
distances_path: null
num_A: 1
merge_consecutive: False

# NEW: Enhanced method specific parameters
max_rank: 512              # Reduced max rank for memory efficiency
variance_threshold: 0.98   # Higher threshold for better compression

# Evaluation settings
tasks: "default"