# Enhanced Cosine Method Configuration - Optimized for Speed and Stability
method: "enhanced_cosine"
model_path: "meta-llama/Meta-Llama-3-8B-Instruct"
dataset: "Open-Orca/SlimOrca"
dataset_column: "text"
batch_size: 4
max_length: 1024
layers_to_skip: 4
dataset_size: 4000  # Further reduced for faster testing
dataset_subset: "train"
use_4bit: True
save_path: null
min_distance_layer: 20
save_transform_only: True
loss: "cosine"
distances_path: null
num_A: 1
merge_consecutive: False

# Enhanced method specific parameters - Optimized
max_rank: 128              # Reduced for faster computation
variance_threshold: 0.98   # Higher threshold for better compression

# Evaluation settings
tasks: "default"