# Kronecker Factorization Configuration
method: "kronecker"  # New method type
model_path: "meta-llama/Meta-Llama-3-8B-Instruct"
dataset: "Open-Orca/SlimOrca"
dataset_column: "text"
batch_size: 4
max_length: 512
layers_to_skip: 4
dataset_size: 2000
dataset_subset: "train"
use_4bit: True
save_path: null
min_distance_layer: 20
save_transform_only: True

# Kronecker-specific parameters
rank_ratio: 0.25          # Compression ratio (0.1-0.5)
max_iterations: 5        # Optimization iterations
loss: "cosine"            # Loss function: cosine, mse

# Standard parameters (kept for compatibility)
diag: False
two_vectors: False
thri: False
solver: "adam"            # Not used in Kronecker but kept for compatibility
distances_path: null
num_A: 1
merge_consecutive: False
accurate: False

# Evaluation tasks (optional - specify which benchmarks to run)
tasks:
  winogrande:
    fewshots: 5
  boolq:
    fewshots: 0
  piqa: 
    fewshots: 0
  # race:
  #   fewshots: 0
  # sciq:
  #   fewshots: 0
  # openbookqa:
  #   fewshots: 0