method: "smart_init"
model_path: "meta-llama/Meta-Llama-3-8B-Instruct"
dataset: "Open-Orca/SlimOrca"
dataset_column: "text"
batch_size: 8
max_length: 1024
layers_to_skip: 8
dataset_size: 4000
dataset_subset: "train"
use_4bit: True
save_path: null
distances_path: "distances_8layer.pth"
num_A: 1
merge_consecutive: False

# Smart initialization specific parameters
init_method: "least_squares"  # Options: least_squares, pca_guided, residual_aware
loss_type: "combined"  # Options: cosine, mse, combined
fine_tune_epochs: 10  # Fewer epochs needed with good init