# teacher_guided_pipeline.yaml
method: "teacher_guided"
model_path: "meta-llama/Meta-Llama-3-8B-Instruct"
dataset: "Open-Orca/SlimOrca"
dataset_column: "text"
batch_size: 8
max_length: 1024
layers_to_skip: 8
dataset_size: 4000
dataset_subset: "train"
use_4bit: True
save_path: null
min_distance_layer: 20

# Teacher-specific parameters
teacher_weight: 0.3  # How much to weight teacher loss (0.0 to 1.0)
lr: 0.0001            # Learning rate for optimization
epochs: 5          # Number of optimization epochs

# Block selection
distances_path: "distances.pth"
num_A: 1
merge_consecutive: False