method: "gate_aware_coupled"
model_path: "meta-llama/Meta-Llama-3-8B-Instruct"
dataset: "Open-Orca/SlimOrca"
dataset_column: "text"
batch_size: 4
max_length: 512
layers_to_skip: 4
dataset_size: 2000
dataset_subset: "train"
use_4bit: True
save_path: null
min_distance_layer: 20
distances_path: null
num_A: 1
merge_consecutive: False
consistency_weight: 0.1
importance_weight: 1.0
