method: "vib"
loss: "vib" 
beta: 0.1  # 0.01~1.0 범위에서 실험 가능
solver: "adam"
model_path: "meta-llama/Meta-Llama-3-8B-Instruct" # meta-llama/Llama-3.2-3B-Instruct
dataset: "Open-Orca/SlimOrca"
dataset_column: "text"
batch_size: 4 # 8
max_length: 512 # 1024
layers_to_skip: 4
dataset_size: 2000 # 8000
dataset_subset: "train"
use_4bit: True
save_path: null
min_distance_layer: 20
save_transform_only: True
diag: False # whether to force the LT to be a diagonal matrix
two_vectors: False # whether to force the LT to be a multiplication of two vectors
thri: False # whether to force the LT to be a lower triangular matrix
distances_path: null
num_A: 1
merge_consecutive: False 
accurate: False # False will run cosine(xA, y - z) where z is the residual attention info, True to run cosine(xA + z, y)
