# Gate-Aware Coupled Optimization (GACO) Configuration

method: "linear"  # Use our new gate-aware coupled optimization method
model_path: "meta-llama/Meta-Llama-3-8B-Instruct"
dataset: "Open-Orca/SlimOrca"
dataset_column: "text"
batch_size: 4
max_length: 512
layers_to_skip: 4
dataset_size: 1000
dataset_subset: "train"
use_4bit: True
save_path: null
min_distance_layer: 20
token: null  # Add your HuggingFace token here if needed

# Distance computation parameters
distances_path: null  # Will auto-generate if not provided
num_A: 1
merge_consecutive: False

# GACO-specific parameters (for future phases)
gate_importance_weight: 1.0  # Weight for gate importance in optimization
coupling_strength: 0.5       # Strength of coupling between up/down projections
consistency_regularization: 0.1  # Regularization for transformation consistency

# Evaluation parameters (optional)
tasks:
  boolq:
    fewshots: 0
  lambada_openai:
    fewshots: 0

# Debug settings
verbose: True
save_intermediate_results: False
