# adaptive_replaceme.yaml
method: "adaptive"
model_path: "meta-llama/Llama-3.2-3B-Instruct"
dataset: "Open-Orca/SlimOrca"
dataset_column: "text"
batch_size: 4
max_length: 512
layers_to_skip: 4
dataset_size: 4000 # 1000
dataset_subset: "train"
use_4bit: False
save_path: null
min_distance_layer: 20
distances_path: null

# Adaptive-specific parameters
epochs: 10
lr: 0.001
num_A: 1
merge_consecutive: False

# Evaluation tasks
tasks:
  boolq:
    fewshots: 0
  lambada_openai:
    fewshots: 0