method: "spectral"
model_path: "meta-llama/Meta-Llama-3-8B-Instruct"
dataset: "Open-Orca/SlimOrca"
dataset_column: "text"
batch_size: 4
max_length: 1024
layers_to_skip: 8
dataset_size: 4000
dataset_subset: "train"
use_4bit: False
save_path: null
min_distance_layer: 20
distances_path: "distances.pth"

# Spectral regularization specific parameters
spectral_weight: 0.01
condition_weight: 0.001
orth_weight: 0.0001
use_residual: False
epochs: 100

num_A: 1
merge_consecutive: False