method: "conditional_routing"
model_path: "meta-llama/Llama-3.2-3B-Instruct"
dataset: "Open-Orca/SlimOrca"
dataset_column: "text"
batch_size: 4
max_length: 512
layers_to_skip: 4  # Not used but kept for compatibility
dataset_size: 1000
dataset_subset: "train"
use_4bit: False
save_path: null
target_simple_ratio: 0.3  # Target 30% tokens through simple path
target_medium_ratio: 0.5  # Target 50% tokens through medium path
low_rank_dim: 32  # Dimension for low-rank approximation
distances_path: "distances.pth"

tasks:
  boolq:
    fewshots: 0
  lambada_openai:
    fewshots: 0
