method: "alf"
model_path: "meta-llama/Llama-3.2-3B-Instruct"
dataset: "Open-Orca/SlimOrca"
dataset_column: "text"
batch_size: 4
max_length: 512
layers_to_skip: 4
dataset_size: 1000
dataset_subset: "train"
use_4bit: False
save_path: null
min_distance_layer: 20

# Standard parameters
distances_path: "distances.pth"
num_A: 1
merge_consecutive: False

# ALF specific parameters
num_experts: 4              # Number of FFN experts in bank
use_layer_adapters: True    # Use layer-specific adapters
training_epochs: 10         # Training epochs
learning_rate: 0.0001       # Learning rate
warmup_steps: 100          # Warmup steps

# Evaluation
tasks:
  boolq:
    fewshots: 0
  lambada_openai:
    fewshots: 0