method: "mapp"
model_path: "meta-llama/Llama-3.2-3B-Instruct"
dataset: "Open-Orca/SlimOrca"
dataset_column: "text"
batch_size: 4
max_length: 512
dataset_size: 1000
dataset_subset: "train"
use_4bit: False
save_path: null
token: null
distances_path: null

# MAPP specific parameters
pruning_ratio: 0.25  # Remove 25% of layers
max_perplexity_increase: 1.2  # Allow up to 20% perplexity increase

# Evaluation tasks
tasks:
  boolq:
    fewshots: 0
  lambada_openai:
    fewshots: 0