# Replace_Me_pipeline_llava.yaml
method: "cosine"
is_llava: True
model_path: "xtuner/llava-llama-3-8b-v1_1"
dataset: "coco_captions"  # or "llava_instruct"
batch_size: 2  # Smaller for image processing
max_length: 512
layers_to_skip: 8
dataset_size: 1000  # Smaller for faster testing
use_4bit: True
save_path: null
save_transform_only: False
diag: False
two_vectors: False
thri: False
solver: "adam"
loss: "cosine"
distances_path: null
num_A: 1
merge_consecutive: False
accurate: False