method: "residual_scaled"  # 새로운 method
model_path: "meta-llama/Llama-3.2-3B-Instruct"
dataset: "Open-Orca/SlimOrca"
dataset_column: "text"
batch_size: 4
max_length: 512
layers_to_skip: 4
dataset_size: 1000
dataset_subset: "train"
use_4bit: True
save_path: null
min_distance_layer: 20
save_transform_only: True
diag: False
two_vectors: False
thri: False
solver: "adam"
loss: "cosine"
distances_path: null
num_A: 1
merge_consecutive: False
accurate: False
residual_alpha: 1.05  # 1.05로 시작, 필요시 1.08, 1.1로 조정
tasks:
  boolq:
    fewshots: 0
  lambada_openai:
    fewshots: 0