method: "amatr"
model_path: "meta-llama/Llama-3.2-3B-Instruct"
dataset: "Open-Orca/SlimOrca"
dataset_column: "text"
batch_size: 4
max_length: 512
layers_to_skip: 4
dataset_size: 1000
dataset_subset: "train"
use_4bit: True
save_path: null
distances_path: "distances.pth"
num_A: 1
merge_consecutive: False
top_k_tokens: 32  # AMATR specific
apply_compensation: True  # AMATR specific
insert_replacement: False  # Experimental feature
tasks:
  boolq:
    fewshots: 0
  lambada_openai:
    fewshots: 0