method: "ahl"
model_path: "meta-llama/Llama-3.2-3B-Instruct"
dataset: "Open-Orca/SlimOrca"
dataset_column: "text"
batch_size: 4
max_length: 512
dataset_size: 1000
dataset_subset: "train"
use_4bit: False
save_path: null
token: null
distances_path: null

# AHL specific parameters
strategy: "progressive"  # progressive, linear, or uniform
min_heads_ratio: 0.5  # Minimum ratio of heads to keep

# Evaluation tasks
tasks:
  boolq:
    fewshots: 0
  lambada_openai:
    fewshots: 0
  piqa:
    fewshots: 0
  winogrande:
    fewshots: 5