method: "conditional_linear"
model_path: "meta-llama/Llama-3.2-3B-Instruct"
dataset: "Open-Orca/SlimOrca"
dataset_column: "text"
batch_size: 4
max_length: 512
layers_to_skip: 4
dataset_size: 1000
dataset_subset: "train"
use_4bit: True
save_path: null
min_distance_layer: 20
save_transform_only: True
distances_path: null
num_A: 1
merge_consecutive: False
n_clusters: 4  # 클러스터 개수 (2, 4, 8 등으로 실험 가능)
tasks:
  boolq:
    fewshots: 0
  lambada_openai:
    fewshots: 0