method: "two_stage"
model_path: "meta-llama/Llama-3.2-3B-Instruct"
dataset: "Open-Orca/SlimOrca"
dataset_column: "text"
batch_size: 4
max_length: 512
layers_to_skip: 4
dataset_size: 1000
dataset_subset: "train"
use_4bit: True
save_path: null
min_distance_layer: 20
save_transform_only: True
diag: False
two_vectors: False
thri: False
distances_path: "distances.pth"
num_A: 1
merge_consecutive: False
accurate: False
stage1_epochs: 5   # Not used (analytical), but for reference
stage2_epochs: 10  # Fine-tuning epochs
tasks:
  boolq:
    fewshots: 0
  lambada_openai:
    fewshots: 0