method: "regularized_cosine"
model_path: "meta-llama/Llama-3.2-3B-Instruct"
dataset: "Open-Orca/SlimOrca"
dataset_column: "text"
batch_size: 4
max_length: 512
layers_to_skip: 4
dataset_size: 1000
dataset_subset: "train"
use_4bit: True
save_path: null
min_distance_layer: 20
save_transform_only: True
diag: False
two_vectors: False
thri: False
solver: "adam"
loss: "cosine"
distances_path: "distances.pth"
num_A: 1
merge_consecutive: False
accurate: False
regularization: 0.0001  # 1e-4로 설정
tasks:
  boolq:
    fewshots: 0
  lambada_openai:
    fewshots: 0