# ============================================================
# vlm_pipeline_config.yaml 업데이트
# ============================================================
method: "vlm_cosine"
model_path: "lmms-lab/llama3-llava-next-8b"
image_dir: "train2014"
batch_size: 4
max_length: 512
layers_to_skip: 8
dataset_size: 500
use_4bit: True
save_path: null
save_transform_only: True
diag: False
two_vectors: False
thri: False
solver: "adam"
loss: "cosine"
distances_path: null
num_A: 1
merge_consecutive: False
accurate: False
token: null

# VLM Evaluation 설정 추가
eval_tasks:
  - "vqav2"
  - "gqa"
eval_num_samples: 500
eval_batch_size: 4