method: "vlm_modality_aware"
model_path: "llava-hf/llava-1.5-7b-hf"
image_dir: "train2014"
batch_size: 8
max_length: 512
layers_to_skip: 12
dataset_size: 8000
use_4bit: True
save_path: null
save_transform_only: True
lambda_vision: 0.5
lambda_text: 20.0
auto_lambda: False
lr: 0.0001
num_epochs: 10
opt_batch_size: 1024
distances_path: "distances_12.pth"
num_A: 1
merge_consecutive: True
accurate: False
token: null